### ISSUE TITLE
Servless Container API build fails due to incorrect ECR permission

### ISSUE THREAD

**Issue by khneide** [aws-amplify/amplify-category-api#1255]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.19.0

### Amplify CLI Version

10.7.2

### What operating system are you using?

Mac 13.2

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

`amplify api push` fails due to failure of pipeline build step.

Error Message:
```
error pulling image configuration: download failed after attempts=1: 
denied: User: arn:aws:sts::<accountId>:assumed-role/<role>/<session> is not authorized to perform: 
ecr:GetDownloadUrlForLayer on resource: 
arn:aws:ecr:<region>:<account>:repository/<repoName> 
because no identity-based policy allows the ecr:GetDownloadUrlForLayer action

```

This seems to be due to [ecr:BatchGetDownloadUrlForLayer instead of ecr:GetDownloadUrlForLayer](https://github.com/aws-amplify/amplify-category-api/blob/2655d39e27c905abe2aec57468c08ca0eb910cd6/packages/amplify-category-api/src/provider-utils/awscloudformation/pipeline-with-awaiter.ts#L159).  Changing that line of code and using `amplify-dev` locally fixed the build issue.

### Expected behavior

For the container based API to deploy successfully.

### Reproduction steps

1. Enable serverless container deployments using `amplify configure project`
2. Add a new API using `amplify api add`
3. choose `API Gateway + AWS Fargate (Container-based) `
4. choose `custom` for the api template
5. Add code, the resulting directory tree
```
amplify
  -  backend
      -  api
         - foobarApi
            - src
              - db
                - Dockerfile
              - api
                - Dockerfile
                - index.js
                - package.json
              - docker-compose.yml
```
7. The `docker-compose.yml` looks something like this:
```
version: "3.8"
services:
  api:
    # simple express app that pings a Postgres db
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - PORT=8080
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
   # simple postgres DB container
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
```
8. Push api using `amplify api push`
9. Api fails to deploy as mentioned above

**Note**: The reason for the issue is that the `Dockerfile` for `db` container is  like this:
```
FROM <AWS account id>.dkr.ecr.<region>.amazonaws.com/<repo>:<tag>
```
The build fails to pull the above image from ECR due to the permission misconfiguration mentioned above.  It is worth mentioning that the reason I had to wrap the private repo image in a `Dockerfile` is due to using `image` instead of `build` in `docker-compose.yml` does not work either.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.
