### ISSUE TITLE
@manyToMany causing DynamoDB:ValidationException

### ISSUE THREAD

**Issue by zachegnermh** [aws-amplify/amplify-category-api#1275]

**Comment by chrisbonifacio** [comment]
Hi @zachegnermh 👋 thanks for raising this issue! What version of the Amplify CLI were you using when the graphql mutations were generated? I just tried generating the mutations with the last version of the CLI and given schema but my `createDashboard` mutation looks different to yours.

```graphql
export const createDashboard = /* GraphQL */ `
  mutation CreateDashboard(
    $input: CreateDashboardInput!
    $condition: ModelDashboardConditionInput
  ) {
    createDashboard(input: $input, condition: $condition) {
      id
      title
      reports {
        nextToken
        startedAt
      }
      channelId
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
```

Can you try upgrading to the latest version of the Amplify CLI if not already on that version and re-running `amplify codegen`?

**Comment by zachegnermh** [comment]
Hi @chrisbonifacio, thanks for looking into this issue. I had noticed that I was running Amplify CLI version 10.6.2, so I upgraded today to 10.8.1. I erased mock data and reran amplify mock api as well as amplify codegen. I am still facing the same error as before when trying to "createDashboard" and my mutations file has not changed.

```graphql
export const createDashboard = /* GraphQL */ 
  mutation CreateDashboard(
    $input: CreateDashboardInput!
    $condition: ModelDashboardConditionInput
  ) {
    createDashboard(input: $input, condition: $condition) {
      id
      title
      reports {
        items {
          id
          reportID
          dashboardID
          createdAt
          updatedAt
        }
        nextToken
      }
      channelId
      createdAt
      updatedAt
    }
  }
;

**Comment by chrisbonifacio** [comment]
@zachegnermh Of course :) Maybe our codegens are configured differently. Can you share your `graphqlconfig.yml` file?

**Comment by zachegnermh** [comment]
@chrisbonifacio, here is my `graphqlconfig.yml`, `maxDepth` isn't set here.
```yml
projects:
  mrms:
    schemaPath: amplify/backend/api/mrms/build/schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
```

As to the `reportID` and `dashboardID`, I am not sure where this is coming from. The only instances of this in my code are in the autogenerated graphQL files.

I am also facing the same error in graphiQL
![image](https://user-images.githubusercontent.com/109542090/224091012-6e342c49-6e4b-4c74-b03e-ce6ee4375aa9.png)

Here's is trying with `reportId` and `dashboardId`
![image](https://user-images.githubusercontent.com/109542090/224090492-01b4ff18-5d64-4b7e-8b5f-33cb3c16b329.png)

And also with querying `reportID` or `dashboardID`
![image](https://user-images.githubusercontent.com/109542090/224091510-d96fb2b2-5318-40a2-90dd-e77b5735225d.png)
