### ISSUE TITLE
Codegen does not produce compilable typescript queries.ts code

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-category-api#1960]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.16.1

### Amplify CLI Version

12.7.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

After running `amplify codgen` to produce typescript code for a graphql API, the queries.ts file does not compile if the GraphQL API has a query function with no parameters. 

Specifically the queries.ts code will have code like so that has a ts error: 

```
` as GeneratedQuery<
  APITypes.GetProductsQueryVariables,
  APITypes.GetProductsQuery
```

The error is `'./graphql-schema' has no exported member APITypes.GetProductsQueryVariables`

If you check the graphql-schema.ts file, you'll see there is no APITypes.GetProductsQueryVariables type defined. I assume because this function has no parameters and therefore there are no input variables to define. 

### Expected behavior

amplify codegen should produce syntactically correct queries.ts file. 

### Reproduction steps

1. Make sure you have a function in your graphql API that does not have any parameters, e.g: 

```
type Query { 
     getProducts: [Product!] @function(name: 'MyLambda-${env}')
}
```

2. Configure your `.graphqlconfig.yml` file to produce typescript graphql schema code like so: 

```
projects:
   myGraphQLSchema:
    schemaPath: amplify/backend/api/MyAPI/build/schema.graphql
    includes:
      - frontend/projects/shared/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: /my-graphql/graphql-schema.ts
        docsFilePath: my-graphql/
        region: us-east-1
        apiId: null
        maxDepth: 7
extensions:
  amplify:
     version: 3
```

3. Run `amplify codegen` and examine the resulting queries.ts file

### Project Identifier

3def1a2bd59d61900f734d59f169a578

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.
