### ISSUE TITLE
Unable to import custom transformer module(graphql-ttl-transformer)

### ISSUE THREAD

**Issue by may215** [aws-amplify/amplify-category-api#606]
Amplify version: 7.6.26
I tried to use several transformers.
This is the error: `
Unable to import custom transformer module(graphql-ttl-transformer).
You may fix this error by editing transformers at /Users/test/projects/amplify/backend/api/datasyabackend/transform.conf.json
✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: Cannot find module '/Users/test/.amplify/lib/node_modules/graphql-ttl-transformer
```
Require stack:
- /snapshot/node_modules/import-global/index.js
- /snapshot/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
- /snapshot/node_modules/amplify-provider-awscloudformation/lib/push-resources.js
- /snapshot/node_modules/amplify-provider-awscloudformation/lib/override-manager/transform-resource.js
- /snapshot/node_modules/amplify-provider-awscloudformation/lib/override-manager/index.js
- /snapshot/node_modules/amplify-provider-awscloudformation/lib/initializer.js
- /snapshot/node_modules/amplify-provider-awscloudformation/lib/index.js
- /snapshot/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/root-stack-status.js
- /snapshot/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status-data.js
- /snapshot/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status-view.js
- /snapshot/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js
- /snapshot/node_modules/@aws-amplify/cli/lib/domain/amplify-toolkit.js
- /snapshot/node_modules/@aws-amplify/cli/lib/domain/context.js
- /snapshot/node_modules/@aws-amplify/cli/lib/context-manager.js
- /snapshot/node_modules/@aws-amplify/cli/lib/index.js
- /snapshot/node_modules/@aws-amplify/cli/bin/amplify
```
I checked this also, but, it's not working for me: https://github.com/flogy/graphql-ttl-transformer/issues/3

What am I missing?

**Comment by josefaidt** [comment]
Hey @may215 :wave: thanks for raising this! Can you share how you've modified the `transform.conf.json` file?

**Comment by francoisharmse777** [comment]
With Amplify CLI v9 

I have the same issue - when deploying to the PROD amplify environment.
Deploy to DEV and TEST was fine. 

Process: 
1. checkout from dev and amplify pull
2. checkout TEST, amplify env checkout TEST and merge DEV into TEST (amplify push if required, since amplify CICD does backend deployment)
3. then commit and deploy to TEST succeeds
4. checkout PROD and amplify env checkout PROD, merge TEST into PROD - amplify backend PROD deployment fails with  below: 

2022-06-29T09:13:01.192Z [INFO]: 🛑 Unable to import custom transformer module(graphql-ttl-transformer).
2022-06-29T09:13:01.192Z [INFO]: 🛑 You may fix this error by editing transformers at graphql-ttl-transformer/transform.conf.json

one way I fix this is to do an "npm install" in the git repo folder, and then a git push to PROD again
this is not correct since the amplify CICD pipeline includes a step "npm ci" already (why is this not working as expected?)

**Comment by josefaidt** [comment]
Hey @francoisharmse777 :wave: apologies for the delay here! Are you still experiencing this issue? Was this caused by a missing Node module? 
> one way I fix this is to do an "npm install" in the git repo folder, and then a git push to PROD again

**Comment by LoukasGP** [comment]
I am also experiencing this issue:

1. I have read this article offering a [build solution](https://github.com/flogy/graphql-ttl-transformer/issues/3).
2. I have added this to my transform.conf.json file `"transformers": ["graphql-ttl-transformer"]`
3. I have installed this package on my project `"graphql-ttl-transformer": "^2.0.0",`
4. The localhost ttl fields via graphql schema work and show in DynamoDB
5. I am using Next.js and AWS Amplify

**Error:**
🛑 Unable to import custom transformer module(graphql-ttl-transformer).
🛑 You may fix this error by editing transformers at graphql-ttl-transformer/transform.conf.json

Build File:
```
version: 1
backend:
  phases:
    build:
      commands:
        - npm i -S graphql-ttl-transformer
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm i
    build:
      commands:
        - npm run build
        - amplifyPush --simple
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
```

**Comment by josefaidt** [comment]
Hey @may215 and @LoukasGP :wave: apologies for the delay! I was able to reproduce this in a small app using the git-connected CI/CD workflow to deploy with Amplify Hosting; using the following steps:

1. `amplify init -y`
2. add a sample GraphQL API, accepting defaults -- `amplify add api`
3. install the transformer to the project with `npm init -y; npm install graphql-ttl-transformer`
4. add to `transform.conf.json`:
	```json
	  {
	    "Version": 5,
	    "ElasticsearchWarning": true,
	    "transformers": ["graphql-ttl-transformer"]
	  }
	```
5. create a git repo, add hosting with `amplify add hosting`
6. use the following buildspec file (`amplify.yml`):
	  ```yml
	  version: 1
	  backend:
	    phases:
	      build:
	        commands:
	          - npm ci
	          - amplifyPush --simple
	  frontend:
	    phases:
	      # IMPORTANT - Please verify your build commands
	      build:
	        commands: []
	    artifacts:
	      # IMPORTANT - Please verify your build output directory
	      baseDirectory: /
	      files:
	        - '**/*'
	    cache:
	      paths: []
	  ```
7. `amplify push` and observe no error
8. `git push` and observe error

Marking as a bug 🙂

**Comment by olliethedev** [comment]
I see this issue with a custom v2 transformer as well.

**Comment by joekiller** [comment]
Hello,

I had a problem with this as well. I was able to overcome it by installing the plugin prior to the `amplifyPush` both locally and globally. Sheesh.

```
version: 1
backend:
  phases:
    build:
      commands:
        - npm install -g graphql-ttl-transformer
        - npm install graphql-ttl-transformer
        - amplifyPush --simple
```

**Comment by timatperfectco** [comment]
+1; thanks much @josefaidt for the [reliable reproduction steps](https://github.com/aws-amplify/amplify-category-api/issues/606#issuecomment-1230856919) of this bug.  I’ve reproduced the issue myself using those steps, and the error message and stack trace is:

```
🛑 Unable to import custom transformer module(graphql-ttl-transformer).
🛑 You may fix this error by editing transformers at graphql-ttl-transformer/transform.conf.json
```

This is the same wording as @LoukasGP and @francoisharmse777 and @josefaidt ; However note OP @may215 had a slightly different textual location reference for the transform:

```
Unable to import custom transformer module(graphql-ttl-transformer).
You may fix this error by editing transformers at /Users/test/projects/amplify/backend/api/datasyabackend/transform.conf.json
```

My [stack trace](https://github.com/aws-amplify/amplify-category-api/files/9501457/noTtlThruCicdAmplify_stacktrace.txt) also differs considerably from OP, but this is the stack trace provided by the reproduction steps linked above.

**Comment by joekiller** [comment]
> if you are looking for support in the v2 transformer version, I would suggest creating a feature request in this repository: https://github.com/flogy/graphql-ttl-transformer

The readme indicates that v2 is supported as it states:

>npm install --save graphql-ttl-transformer
For projects using the old GraphQL Transformer v1 run:
npm install --save graphql-ttl-transformer@1

I have had success, alas with the wrenching I mentioned prior, running transformersversion 2.

**Comment by joekiller** [comment]
Being that the [Amplify CLI plugin installation docs](https://docs.amplify.aws/cli/plugins/plugins/#plugin-installation) explicitly require the plugin to be installed globally it seems reasonable that one may also need to globally install the plugin during CI as the environment otherwise doesn't have the plugin available in the same node_module environment as the CLI tool itself.

**Comment by timatperfectco** [comment]
Great links, @joekiller !  I suspect something similar to the MacOS [cross-node_modules issue you mention](https://github.com/aws-amplify/amplify-category-api/issues/606#issuecomment-1239542869) is also occurring in the AWS Amplify CI/CD backend deployment process.   When that process [is governed according to your global install suggestion](https://github.com/timatperfectco/ttl-breaks-amplify-cicd/blob/412d5edbe119625c4e8af195e75c4e61dee70c74/amplify.yml) via  `amplify.yml` at root of project:

```
version: 1
backend:
  phases:
    build:
      commands:
        - npm i -g graphql-ttl-transformer
        - npm ci
        - amplifyPush --simple
frontend:
  phases:
    # IMPORTANT - Please verify your build commands
    build:
      commands: []
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /
    files:
      - '**/*'
  cache:
    paths: []
```

sadly, the Amplify console for the app's backend deployment gives [the same error](https://github.com/aws-amplify/amplify-category-api/files/9507615/20220907_1528Z_joekiller_suggestion_no_help.txt) as in the [reproduction steps of the issue, in the context of Amplify CI/CD application backend deployment](https://github.com/aws-amplify/amplify-category-api/issues/606#issuecomment-1230856919).

**Comment by joekiller** [comment]
@timatperfectco please note that you must also have the transformer dependency installed in the local node_modules as well. It's unclear if that's the case for your installation as I do not see the line explicitly installing it prior to running `amplifyPush --simple` and cannot tell what the `package.json` contains that `npm ci` would install.

Do one of the following: 

1. `npm install --save-dev graphql-ttl-transformer` in the project, which would then let the `npm ci` command get the dependency prior to `amplifyPush --simple` or, 
2. replace npm ci with `npm install  graphql-ttl-transformer` and give it a try.

You shouldn't need to run `npm ci` prior to the push which is why in my prior suggestion I just included the following two commands prior to the `amplifyPush`.

```
        - npm install -g graphql-ttl-transformer
        - npm install graphql-ttl-transformer
```

**Comment by timatperfectco** [comment]
@joekiller Thank you for pursuing this!  It's likely something similar that I'm seeing, but sadly your latest suggestions still leave me blocked.

The `package.json` had `graphql-ttl-transformer` as a non-dev dependency due to step 3 in [the reproduction steps](https://github.com/aws-amplify/amplify-category-api/issues/606#issuecomment-1230856919), and so should have included its install during `ci`.  But just to be sure, I tried your suggestion of [moving it to devDependencies in package.json and trying `ci` again](https://github.com/timatperfectco/ttl-breaks-amplify-cicd/commit/ebb0b4f71dd8e2fcf04f9d26617bda3fdd41e1ff),  and of [replacing the `ci` invocation with an `i` invocation](https://github.com/timatperfectco/ttl-breaks-amplify-cicd/blob/9d3efeee592bfb71c6f755c4eeb09a99b8cfa396/amplify.yml) [without luck](https://github.com/aws-amplify/amplify-category-api/files/9508796/20220907_1806Z_joekiller_no_ci_just_glob_and_loc_install_at_amplify_latest.txt), and with [an `i --save-dev` invocation](https://github.com/timatperfectco/ttl-breaks-amplify-cicd/blob/435678b0ffa3152361ef306d707859ab7b4c7566/amplify.yml)
[but still no luck](https://github.com/aws-amplify/amplify-category-api/files/9508804/20220907_1840Z_joekiller_no_ci_just_glob_and_loc_devdep_install.txt).

Turning out to be a very difficult situation; TTL on dynamoDb is a critical feature for my serverless app.   Amplify backend CI/CD worked fine... until TTL on dynamoDb was added.  That broke Amplify backend CI/CD, despite that I can `amplify push` just fine.

It's starting to seem like I have to give up on Amplify CI/CD for the backend _at all_ for my application, since TTL is a needed feature and works fine but breaks Amplify backend CI/CD.

**Comment by joekiller** [comment]
@timatperfectco yes totally lame that "it works for me" and not for you.

I'll admit that I left out a trick in the bag and should validate the approcate with the "steps to replicate" mentioned earlier to confirm the fixing.

So trick left out that may be affecting it and I didn't realize it b/c I took it back out of my build is the following:

Within the amplify console for your project there are "environmental variables" and within those variables there is one called `_LIVE_UPDATES` which you can manipulate to get Amplify to update programs on your build image.

![image](https://user-images.githubusercontent.com/1022919/188985875-d7c5f2c8-8f2e-48fa-8189-b6714a816121.png)

If the option isn't there, you likely need to go under "build settings" instead and then click "Edit" under "Build image settings"
![image](https://user-images.githubusercontent.com/1022919/188986633-c1c39b60-dc0a-4bcd-bc97-4e3669a47b76.png)

![image](https://user-images.githubusercontent.com/1022919/188986805-dd34e9dc-1f98-4946-bb43-b7c8c26894cb.png)

Tell the image settings to update the amplify cli at least, I chose v9.2.1 but I think 10.0.0 is out now. I also used node version 16.

![image](https://user-images.githubusercontent.com/1022919/188987011-6d4268bb-e83a-4c13-82d2-0dd766b64dee.png)

You cannot tell the image to update NPM packages from that screen, but go back to the environmental variables and you should see _LIVE_UPDATES populated with your selections.

![image](https://user-images.githubusercontent.com/1022919/188987418-2eb65b07-ff09-4ffe-951d-2391430fd645.png)

Finally the trick is to update that variable such that you ask for the `graphql-ttl-transformer` to be installed as well:

old:
```
[{"pkg":"@aws-amplify/cli","type":"npm","version":"v9.2.1"},{"pkg":"node","type":"nvm","version":"16"}]
```

new:
```
[{"pkg":"@aws-amplify/cli","type":"npm","version":"v9.2.1"},{"pkg":"node","type":"nvm","version":"16"},{"pkg":"graphql-ttl-transformer","type":"npm","version":"v2.0.0"}]
```


I'll run off now and test on the proof of concept but some combination of these things "make it work for me".

I eventually was able to just run what I suggested so who knows if the previous stuff cached or whatever and I didn't realize it.

**Comment by timatperfectco** [comment]
Regarding `_LIVE_UPDATES`, that looks like a great but parallel potential investigation.  I have not looked at it yet, but I did realize I may not be able to host the frontend with AWS Amplify if I did not also fix this dependency issue.   So I figured maybe [a look at the source](https://github.com/aws-amplify/amplify-category-api/blob/726d45a319d51124118d06145d4b2cd7522a1bd7/packages/amplify-category-api/src/graphql-transformer/transformer-factory.ts#L205-L232) might be more fruitful.

Both @joekiller and I must be hitting line 217, because I'm failing entirely and a global install was crucial to his solution.

The success he is enjoying thus stems from success at line 222.

But my next line is 229 vs his 227.

I would rather simply install the transformer wherever `pathManager.findProjectRoot()` thinks it should be, so that I never hit line 217 at all.  But  [looking at it](https://github.com/aws-amplify/amplify-cli/blob/ee13aa26bff2def27a370a12be01dda8742556d6/packages/amplify-cli-core/src/state-manager/pathManager.ts#L306-L326) scared me off from trying to discover what path it might be from code inspection, and sadly there are no helpful log messages indicating what that value is.

So, back to the "succeed like @joekiller did" approach: I determined using [successive ls commands](https://github.com/timatperfectco/ttl-breaks-amplify-cicd/blob/b6a7e0ea589888528af930abdd03370cad500348/amplify.yml#L6-L31) that the global location that `npm i -g` installs to is `/root/.nvm/versions/node/v14.19.0/lib/node_modules`

But where the transformerFactory is looking for it, "globally", i.e. after having hit line 217, is `/root/.amplify/lib/node_modules`, per the stack trace in the build failure output (from the "global" approach, since the findProjectRoot approach utterly swallows any error it faced).

So here's a hack replacement for [step 6 in the reproduction steps](https://github.com/aws-amplify/amplify-category-api/issues/606#issuecomment-1230856919) that goes ahead and installs the transformer where the subsystem thinks "global" things go:


```
version: 1
backend:
  phases:
    build:
      commands:
        - npm i graphql-ttl-transformer amplify-prompts@^2.0.1 --prefix /root/.amplify/lib
        - npm ci
        - amplifyPush --simple
frontend:
  phases:
    # IMPORTANT - Please verify your build commands
    build:
      commands: []
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /
    files:
      - '**/*'
  cache:
    paths: []
```

The difference is the single added line:

```
        - npm i graphql-ttl-transformer amplify-prompts@^2.0.1 --prefix /root/.amplify/lib
```

As hacks go, I am not proud of this one.  This makes the build process incredibly brittle, because `/root/.amplify/lib` does not seem like the right place for this code to go, as there is no `node_modules` there already.  It's truly a weird misuse of the tools, but, it fixes the backend deploy that fails from those steps!  I'll try the approach on my own real app and follow-up soon.

**Comment by timatperfectco** [comment]
reversing the order, so that the `--prefix /root/.amplify/lib` hack was after `npm ci`, was necessary to fix my real app:
```
backend:
  phases:
    build:
      commands:
        - npm ci
        - npm i graphql-ttl-transformer amplify-prompts@^2.0.1 --prefix /root/.amplify/lib
        - amplifyPush --simple
```

however, I think this may be overkill because it places all dependencies from `package.json`, as well as `graphql-ttl-transformer` and `amplify-prompts` (to resolve a peer-dependency issue using npm v6) there in `/root/.amplify/lib/node_modules`.

**Comment by joekiller** [comment]
@timatperfectco I have twiddled with the proof of concept some and I think I have a satisfactory workaround for all. Following the steps to replicate, if you simply upgrade npm first, it will work. 

So given the steps to replicate being:

```
version: 1
backend:
  phases:
    build:
      commands:
        - npm ci
        - amplifyPush --simple
```

Prepend to the build phase the command: `npm install -g npm@latest` such that the spec reads:

```
version: 1
backend:
  phases:
    build:
      commands:
        - npm install -g npm@latest
        - npm ci
        - amplifyPush --simple
```

and I have found this works.

I think my upgrade our node to version 16 may have masked the need for this. Also note that the global install is not necessary either. The npm version that was there by default is `6.14.16` and the version upgraded to was `8.19.1` which appears to work fine. On my local machine my version is `8.11.0` so that is likely why it works locally as well.

Hope you find success!
