### ISSUE TITLE
Add support for .NET version 6 runtime for the functions and REST - API Amplify categories

### ISSUE THREAD

**Issue by abdallahshaban557** [aws-amplify/amplify-category-api#81]

**Comment by chrisac309** [comment]
Since .NET Core 3.1 LTS is scheduled for EOL in less than 2 months, are there any updates on a timeline for this yet?  The inability to upgrade to .NET 6.0 is causing dependency issues within my application :(

**Comment by lomaky** [comment]
> Since .NET Core 3.1 LTS is scheduled for EOL in less than 2 months, are there any updates on a timeline for this yet? The inability to upgrade to .NET 6.0 is causing dependency issues within my application :(

We decided a couple of things because of the lack of support for .net in Amplify

1. Migrate the lambdas to Node + TS, which has been incredibly easy. I have not had significant issues and the learning curve is almost flat
2. Migrate the CI/CD pipeline to CodeBuild + CodeDeploy using CDK. 

Amplify is great for starting new projects, but once they get traction is better to move out.

**Comment by ludovicoserrani-nautes** [comment]
I started to get deprecation warnings during build phase:

```bash
⚠️ .NET Core 3.1 is deprecated. Migrate your function at ... to .NET 6
```

I tried to migrate following the instructions at <https://aws.amazon.com/it/blogs/compute/introducing-the-net-6-runtime-for-aws-lambda/> but I get build errors because .NET 6 is not installed in the default build image:

```bash
🛑 Command failed with exit code 145: dotnet publish -c Release -o ...
A compatible installed .NET Core SDK for global.json version [6.0.400] from [.../src/global.json] was not found
Install the [6.0.400] .NET Core SDK or update [.../src/global.json] with an installed .NET Core SDK:
3.1.416 [/usr/share/dotnet/sdk]
```
Can the team at least include .NET 6 in the default build image for those who want to migrate manually?

**Comment by chrisac309** [comment]
From AWS:

> We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using the .NET Core 3.1 runtime.
We are ending support for .NET Core 3.1 in AWS Lambda. This follows .NET Core 3.1 End-Of-Life (EOL) reached on December 13, 2022 [1].
As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two > stages. Starting April 3, 2023, Lambda will no longer apply security patches and other updates to the .NET Core 3.1 runtime used by Lambda functions, and functions using .NET Core 3.1 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the .NET Core 3.1 runtime.
Starting May 3, 2023, you will no longer be able to update existing functions using the .NET Core 3.1 runtime.
We recommend that you upgrade your existing .NET Core 3.1 functions to .NET 6 before April 3, 2023.
End of support does not impact function execution. Your functions will continue to run. However, they will be running on an unsupported runtime which is no longer maintained or patched by the AWS Lambda team.

Starting April 3, if AWS Amplify remains on .NET Core 3.1, Lambda functions will be _unable to be created_, essentially becoming broken functionality.

Additionally, if nothing is done by May 3rd, _all users using AWS Amplify with C# lambda functions will be unable to update their lambda functions_. This is starting to become a larger problem as time goes on.  Is this on the Amplify team's radar?

**Comment by khanjal** [comment]
Ran into this issue too and have been unable to find a fix for it: 
`
        Install the [6.0.100] .NET Core SDK or update [/codebuild/output/src338987957/src/gig-logger/amplify/backend/function/GigLoggerService/src/global.json] with an installed .NET Core SDK:
                                 3.1.426 [/usr/share/dotnet/sdk]
                                 Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/`

**Comment by ludovicoserrani-nautes** [comment]
> 

In the end I temporarily solved modifying the `amplify.yml` in this way:

```yaml
...
backend:
  phases:
    build:
      commands:
        - yum -y install dotnet-host-6.0.15
        - yum -y install dotnet-sdk-6.0
        - dotnet tool install -g Amazon.Lambda.TestTool-6.0
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
...
```

It's not the most efficient solution (the packages are installed in each build) but it works.

**Comment by ludovicoserrani-nautes** [comment]
@grundmanise me and my collegue had the same problem today. 

It seems that the official Microsoft package repository (https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm) has some wrong dependecies for the latest .net 6 version.

We solved like this:

```yaml
...
backend:
  phases:
    build:
      commands:
        - yum install -y yum-utils
        - rpm -Uvh --nodeps $(repoquery --location dotnet-sdk-6.0)
        - rpm -Uvh --nodeps $(repoquery --location dotnet-runtime-6.0)
        - rpm -Uvh --nodeps $(repoquery --location dotnet-runtime-deps-6.0)
        - yum update -y
        - yum -y install dotnet-host-6.0.15
        - yum -y install dotnet-sdk-6.0
        - yum install -y dotnet-runtime-6.0
        - yum install -y dotnet-runtime-deps-6.0
        - yum install -y dotnet-hostfxr-6.0
        - yum install -y dotnet-apphost-pack-6.0
        - yum install -y dotnet-targeting-pack-6.0
        - dotnet tool install -g Amazon.Lambda.TestTool-6.0
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
...  
```

You may need to adjust the commands if you use ASP.NET Core (you can find the complete list of available Microsoft packages here https://packages.microsoft.com/centos/7/prod/Packages/).
